### PR TITLE
fix reset on day component . (fixes #1311 )

### LINKED ISSUE #1311: When executing a 'reset' action in a form containing a 'Day' component, the day component value is not being reset
Expected behavior :  The month, day and year text boxes should be reset to empty

Current behavior : the 3 values not affected.

fiddle : http://jsfiddle.net/1kwdqf5h/

version : 3.20.17

Form Payload : 
`{
    "display": "form",
    "components": [
        {
            "label": "Day",
            "hideInputLabels": false,
            "inputsLabelPosition": "top",
            "fields": {
                "day": {
                    "hide": false,
                    "type": "number"
                },
                "month": {
                    "hide": false,
                    "type": "select"
                },
                "year": {
                    "hide": false,
                    "type": "number"
                }
            },
            "useLocaleSettings": false,
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "day",
            "input": true,
            "key": "day2",
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "reorder": false,
            "encrypted": false,
            "maxDate": "",
            "minDate": "",
            "properties": {},
            "customConditional": "",
            "logic": []
        },
        {
            "type": "button",
            "label": "Submit",
            "key": "submit",
            "disableOnInvalid": true,
            "theme": "primary",
            "input": true,
            "tableView": true
        },
        {
            "label": "Reset",
            "action": "reset",
            "state": "",
            "theme": "danger",
            "shortcut": "",
            "mask": false,
            "tableView": true,
            "alwaysEnabled": false,
            "type": "button",
            "input": true,
            "key": "reset",
            "defaultValue": false,
            "validate": {
                "customMessage": "",
                "json": ""
            },
            "conditional": {
                "show": "",
                "when": "",
                "json": ""
            },
            "showValidations": false,
            "event": "",
            "url": "",
            "custom": "",
            "reorder": false,
            "encrypted": false,
            "properties": {},
            "customConditional": "",
            "logic": []
        }
    ],
    "settings": {
        "pdf": {
            "id": "1ec0f8ee-6685-5d98-a847-26f67b67d6f0",
            "src": "https://files.form.io/pdf/5692b91fd1028f01000407e3/file/1ec0f8ee-6685-5d98-a847-26f67b67d6f0"
        }
    }
}`
Thank you

### PR DESCRIPTION
**Pull request by ASmeha**

### CODE REVIEW

File: src/components/day/Day.js [hunk 1]
```diff
@@ -414,6 +414,12 @@ export default class DayComponent extends BaseComponent {
     }
   }
 
+  resetValue() {
+    const emptyValue = '00/00/0000';
```
Comment (travist) [inline src/components/day/Day.js]: I believe it would be better to just implement the ```emptyValue``` setter like so.

```
get emptyValue() {
  return '00/00/0000';
}
```

Comment (ASmeha) [reply src/components/day/Day.js]: Done 👍

Comment (ASmeha) [reply src/components/day/Day.js]: Hi @travist , kindly can you take a look again ?

**Comment by travist** [comment]
Looks good. thanks.
